import "./globals.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Décor Dreams",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: "Lustria",
          background: "rgba(182, 151, 120, 0.2)",
        }}
      >
        {children}
      </body>
    </html>
  );
}
